mySite/mySite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('newsApp.urls', namespace='newsApp')),
    url(r'^admin/', include(admin.site.urls)),
]

mySite/newsApp/urls.py
from django.conf.urls import patterns, url
from .views import ArticleList, ArticleCreate

urlpatterns = patterns('',
    url(r'^$', ArticleList.as_view(), name='articles'),
    url(r'^create/$', ArticleCreate.as_view(), name='create'),
)

mySite/newsApp/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

mySite/newsApp/views.py
from django.views.generic import ListView, CreateView
from .models import Article

class ArticleList(ListView):
    model = Article

class ArticleCreate(CreateView):
    model = Article
    fields = ['title', 'content']
    success_url = '/'

mySite/newsApp/templates/newsApp/article_form.html
{% extends 'newsApp/base.html' %}
{% block title %}New Article{% endblock %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>
{% endblock %}

mySite/newsApp/templates/newsApp/article_list.html
{% extends 'newsApp/base.html' %}
{% block title %}Articles{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Articles</h1>
      </div>
      {% for article in article_list %}
      <h2>{{ article.title }}</h2>
      <div class="well">
        {{ article.content }}
      </div>
      {% endfor %}
      <p><a href='{% url "newsApp:create" %}'>New Article</a></p>
{% endblock %}

mySite/newsApp/templates/newsApp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container" role="main">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>